backend:
  name: github
  repo: codegram/nuxt-starter
  branch: main
  use_graphql: true

media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About'
        name: 'about'
        file: 'content/pages/about.md'
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Content, name: body, widget: markdown }
