name: Sync variants
on:
  push:
    branches:
      - 'main'
jobs:
  sync-variant/tailwind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> variant/tailwind
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: variant/tailwind
          github_token: ${{ github.token }}